Total_courses = [
    "Engineering Chemistry (Theory)",
    "Calculus (Theory)",
    "Differential Equations and Transforms (Theory)",
    "Complex Variables and Linear Algebra (Theory)",
    "Probability and Statistics (Theory)",
    "Engineering Physics (Theory)",
    "Computer Programming: Python Embedded (Theory and Lab)",
    "Structured and Object-Oriented Programming (Theory Only)",
    "Computer Programming: Java Embedded (Theory and Lab)",
    "Basic Electrical and Electronics Engineering (Theory Only)",
    "Technical English Communication (Theory Only)",
    "Foreign Language Basket",
    "HSM Elective Basket",
    "Quantitative Skills Practice I Soft Skill : 101",
    "Quantitative Skills Practice II Soft Skill : 102",
    "Qualitative Skills Practice I Soft Skill : 201",
    "Qualitative Skills Practice II Soft Skill : 202",
    "Digital Systems Design (Theory Only)",
    "Microprocessors and Microcontrollers (Theory Only)",
    "Discrete Mathematics and Graph Theory (Theory Only)",
    "Data Structures and Algorithms (Theory Only)",
    "Web Programming Embedded (Theory and Lab)",
    "Design and Analysis of Algorithms (Theory Only)",
    "Computer Architecture and Organization (Theory Only)",
    "Software Engineering (Theory Only)",
    "Database Systems (Theory Only)",
    "Operating Systems (Theory Only)",
    "Theory of Computation (Theory Only)",
    "Embedded Systems (Theory Only)",
    "Artificial Intelligence (Theory Only)",
    "Compiler Design (Theory Only)",
    "Computer Networks (Theory Only)",
    "Cryptography and Network Security (Theory Only)",
    "Machine Learning (Theory Only)",
    "Deep Learning (Theory Only)",
    "Game Programming (Theory Only)",
    "Machine Vision (Theory Only)",
    "Explainable Artificial Intelligence (Theory Only)"
]


Total_faculties = [
    "Dr. Aditi Sharma",
    "Prof. Ankit Patel",
    "Dr. Rahul Verma",
    "Prof. Tanvi Kapoor",
    "Dr. Rajat Gupta",
    "Prof. Shruti Singh",
    "Dr. Rakesh Kumar",
    "Prof. Meera Sharma",
    "Dr. Sanjay Verma",
    "Prof. Nisha Kapoor",
    "Dr. Akash Kumar",
    "Prof. Kavita Singh",
    "Dr. Neeraj Desai",
    "Prof. Varsha Mehta",
    "Dr. Anurag Sharma",
    "Prof. Pooja Patel",
    "Dr. Deepika Verma",
    "Prof. Arjun Singh",
    "Dr. Aarti Deshmukh",
    "Prof. Rajan Gupta",
    "Dr. Manisha Kumar",
    "Prof. Sameer Sharma",
    "Dr. Anjali Verma",
    "Prof. Raghav Kapoor",
    "Dr. Neha Kumar",
    "Prof. Sushil Patel",
    "Dr. Radhika Sharma",
    "Prof. Vinita Verma",
    "Dr. Rohit Kapoor",
    "Prof. Shraddha Singh",
    "Dr. Karan Desai",
    "Prof. Vandana Sharma",
    "Dr. Manoj Verma",
    "Prof. Ritu Kumar",
    "Dr. Akshay Patel",
    "Prof. Neha Kapoor",
    "Dr. Sumit Sharma",
    "Prof. Sangeeta Verma",
    "Dr. Anju Gupta",
    "Prof. Vivek Verma",
    "Dr. Sneha Patel",
    "Prof. Abhishek Kumar",
    "Dr. Kirti Verma",
    "Prof. Pankaj Patel",
    "Dr. Akshay Verma",
    "Prof. Priya Sharma",
    "Dr. Alok Kumar",
    "Prof. Vipul Verma",
    "Dr. Sakshi Gupta",
    "Prof. Rishi Patel",
    "Dr. Anjali Kapoor",
    "Prof. Arjun Verma",
    "Dr. Tanvi Desai",
    "Prof. Neha Singh",
    "Dr. Pradeep Sharma",
    "Prof. Meenal Patel",
    "Dr. Anjali Singh",
    "Prof. Rajat Kumar",
    "Dr. Shweta Sharma",
    "Prof. Vivek Sharma",
    "Dr. Snehal Desai",
    "Prof. Neha Verma",
    "Dr. Akash Patel",
    "Prof. Roshni Gupta",
    "Dr. Mohit Kapoor",
    "Prof. Aarti Mehta",
    "Dr. Arvind Deshmukh",
    "Prof. Preeti Khanna",
    "Dr. Sameera Joshi",
    "Prof. Manoj Kumar",
    "Dr. Kirti Sharma",
    "Prof. Abhinav Gupta",
    "Dr. Megha Sharma",
    "Prof. Varun Singh",
    "Dr. Komal Patel",
    "Prof. Naveen Verma",
    "Dr. Ananya Sharma",
    "Prof. Rajesh Kumar",
    "Dr. Priya Gupta",
    "Prof. Vivek Patel",
    "Dr. Sneha Singh",
    "Prof. Manish Verma",
    "Dr. Aishwarya Desai",
    "Prof. Rahul Kapoor",
    "Dr. Nisha Jain",
    "Prof. Vikram Singh",
    "Dr. Arjun Mehta",
    "Prof. Ritu Khanna",
    "Dr. Sameer Joshi",
    "Prof. Leela Sharma",
    "Dr. Karan Kapoor",
    "Prof. Kavita Mehta",
    "Dr. Rakesh Deshmukh",
    "Prof. Neha Gupta",
    "Dr. Deepak Sharma",
    "Prof. Pooja Verma"
]
